"""Eliminar id_cliente de Comanda

Revision ID: 13b81ef5d5ee
Revises: 19832637fb1f
Create Date: 2025-11-24 15:06:07.317196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b81ef5d5ee'
down_revision = '19832637fb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comanda_id_cliente_fkey'), type_='foreignkey')
        batch_op.drop_column('id_cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('comanda_id_cliente_fkey'), 'cliente', ['id_cliente'], ['id_cliente'])

    # ### end Alembic commands ###
