"""mis nuevos cambios

Revision ID: 19832637fb1f
Revises: 7cfc41cbaa41
Create Date: 2025-11-24 17:26:28.435803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19832637fb1f'
down_revision = '7cfc41cbaa41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medio_pago',
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_medio_pago'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('comanda',
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('fecha_cierre', sa.String(length=50), nullable=True),
    sa.Column('id_mozo', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesa.id_mesa'], ),
    sa.ForeignKeyConstraint(['id_mozo'], ['mozo.id'], ),
    sa.PrimaryKeyConstraint('id_comanda')
    )
    op.create_table('detalle_comanda',
    sa.Column('id_detalle_comanda', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=True),
    sa.Column('id_detalle_reserva', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id_comanda'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle_comanda')
    )
    op.create_table('factura',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id_comanda'], ),
    sa.PrimaryKeyConstraint('id_factura'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('detalle_factura',
    sa.Column('id_detalle_factura', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_detalle_comanda', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_detalle_comanda'], ['detalle_comanda.id_detalle_comanda'], ),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id_factura'], ),
    sa.PrimaryKeyConstraint('id_detalle_factura')
    )
    with op.batch_alter_table('bebida', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bebida_producto', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['id_bebida'], ['id_producto'])

    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plato_producto', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['id_plato'], ['id_producto'])

    with op.batch_alter_table('postre', schema=None) as batch_op:
        batch_op.drop_constraint('fk_postre_producto', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['id_postre'], ['id_producto'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_producto_seccion', type_='foreignkey')
        batch_op.create_foreign_key(None, 'seccion', ['id_seccion'], ['id_seccion'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_producto_seccion', 'seccion', ['id_seccion'], ['id_seccion'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('postre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_postre_producto', 'producto', ['id_postre'], ['id_producto'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_plato_producto', 'producto', ['id_plato'], ['id_producto'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('bebida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_bebida_producto', 'producto', ['id_bebida'], ['id_producto'], onupdate='CASCADE', ondelete='CASCADE')

    op.drop_table('detalle_factura')
    op.drop_table('factura')
    op.drop_table('detalle_comanda')
    op.drop_table('comanda')
    op.drop_table('medio_pago')
    # ### end Alembic commands ###
