"""Initial migration with existing models

Revision ID: 63ae69fd644b
Revises: 
Create Date: 2025-11-03 21:33:45.759487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ae69fd644b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bebida', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bebida_producto', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['id_bebida'], ['id_producto'])

    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plato_producto', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['id_plato'], ['id_producto'])

    with op.batch_alter_table('postre', schema=None) as batch_op:
        batch_op.drop_constraint('fk_postre_producto', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['id_postre'], ['id_producto'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_producto_seccion', type_='foreignkey')
        batch_op.create_foreign_key(None, 'seccion', ['id_seccion'], ['id_seccion'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_producto_seccion', 'seccion', ['id_seccion'], ['id_seccion'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('postre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_postre_producto', 'producto', ['id_postre'], ['id_producto'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_plato_producto', 'producto', ['id_plato'], ['id_producto'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('bebida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_bebida_producto', 'producto', ['id_bebida'], ['id_producto'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
