"""Initial migration clean

Revision ID: 70c6a60ec674
Revises: 
Create Date: 2025-11-25 18:46:50.534264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c6a60ec674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('num_telefono', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('medio_pago',
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_medio_pago'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('seccion',
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_seccion'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sector',
    sa.Column('id_sector', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_sector'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('mesa',
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('cant_comensales', sa.Integer(), nullable=False),
    sa.Column('id_sector', sa.Integer(), nullable=False),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_sector'], ['sector.id_sector'], ),
    sa.PrimaryKeyConstraint('id_mesa'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('mozo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=False),
    sa.Column('nombre_apellido', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('id_sector', sa.Integer(), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_sector'], ['sector.id_sector'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_seccion'], ['seccion.id_seccion'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('bebida',
    sa.Column('id_bebida', sa.Integer(), nullable=False),
    sa.Column('cm3', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_bebida'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_bebida')
    )
    op.create_table('comanda',
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('fecha_cierre', sa.String(length=50), nullable=True),
    sa.Column('id_mozo', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesa.id_mesa'], ),
    sa.ForeignKeyConstraint(['id_mozo'], ['mozo.id'], ),
    sa.PrimaryKeyConstraint('id_comanda')
    )
    op.create_table('plato',
    sa.Column('id_plato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_plato'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_plato')
    )
    op.create_table('postre',
    sa.Column('id_postre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_postre'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_postre')
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.TIMESTAMP(), nullable=False),
    sa.Column('cant_personas', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo_cancelacion', sa.String(length=255), nullable=True),
    sa.Column('senia_devuelta', sa.Boolean(), nullable=True),
    sa.Column('senia_recuperada', sa.Boolean(), nullable=True),
    sa.Column('asistida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesa.id_mesa'], ),
    sa.PrimaryKeyConstraint('id_reserva'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('detalle_comanda',
    sa.Column('id_detalle_comanda', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=True),
    sa.Column('id_detalle_reserva', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id_comanda'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle_comanda')
    )
    op.create_table('factura',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id_comanda'], ),
    sa.PrimaryKeyConstraint('id_factura'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('detalle_factura',
    sa.Column('id_detalle_factura', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_detalle_comanda', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_detalle_comanda'], ['detalle_comanda.id_detalle_comanda'], ),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id_factura'], ),
    sa.PrimaryKeyConstraint('id_detalle_factura')
    )
    op.create_table('pago',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id_factura'], ),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medio_pago.id_medio_pago'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('detalle_factura')
    op.drop_table('factura')
    op.drop_table('detalle_comanda')
    op.drop_table('reserva')
    op.drop_table('postre')
    op.drop_table('plato')
    op.drop_table('comanda')
    op.drop_table('bebida')
    op.drop_table('producto')
    op.drop_table('mozo')
    op.drop_table('mesa')
    op.drop_table('sector')
    op.drop_table('seccion')
    op.drop_table('medio_pago')
    op.drop_table('cliente')
    # ### end Alembic commands ###
