"""Actualizar comanda y crear detalle_comanda

Revision ID: 7cfc41cbaa41
Revises: e3aea5daada9
Create Date: 2025-11-21 13:19:56.638846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfc41cbaa41'
down_revision = 'e3aea5daada9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comanda',
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('fecha_cierre', sa.String(length=50), nullable=True),
    sa.Column('id_mozo', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False, server_default='Abierta'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('baja', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesa.id_mesa'], ),
    sa.ForeignKeyConstraint(['id_mozo'], ['mozo.id'], ),
    sa.PrimaryKeyConstraint('id_comanda')
    )
    op.create_table('detalle_comanda',
    sa.Column('id_detalle_comanda', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=True, server_default='false'),
    sa.Column('id_detalle_reserva', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id_comanda'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle_comanda')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_comanda')
    op.drop_table('comanda')
    # ### end Alembic commands ###
